name: Terraform (AWS)
on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  id-token: write
  contents: read

jobs:
  plan-apply:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: envs/aws/stacks/vm-basic
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::<ACCOUNT_ID>:role/<ROLE_NAME>
          aws-region: ap-northeast-1

      - name: Terraform Init (S3 backend)
        run: terraform init -backend-config=../backend.hcl

      - run: terraform fmt -check
      - run: terraform validate
      - run: terraform plan -input=false

      - if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve -input=false
