name: terraform-apply
on:
  push:
    branches: [main]
    paths:
      - "envs/**"
      - "modules/**"
      - "app/**"
      - "app-landing/**"

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      # PR相当のvalidate（backend無効）
      - name: Terraform Validate (Azure)
        run: |
          terraform -chdir=envs/azure/azure-b1s-mvp init -backend=false
          terraform -chdir=envs/azure/azure-b1s-mvp validate

      # main で apply（SP認証は Secrets から）
      - name: Terraform Apply (Azure)
        env:
          ARM_CLIENT_ID:        ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET:    ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID:  ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID:        ${{ secrets.ARM_TENANT_ID }}
        run: |
          set -euo pipefail
          terraform -chdir=envs/azure/azure-b1s-mvp init
          terraform -chdir=envs/azure/azure-b1s-mvp apply -auto-approve

      # Azure ログイン（このジョブ内で state があるため、この後の output が安定）
      - name: Azure Login (Service Principal)
        uses: azure/login@v2
        with:
          client-id:        ${{ secrets.ARM_CLIENT_ID }}
          tenant-id:        ${{ secrets.ARM_TENANT_ID }}
          subscription-id:  ${{ secrets.ARM_SUBSCRIPTION_ID }}
          client-secret:    ${{ secrets.ARM_CLIENT_SECRET }}

      - name: Preflight - Verify Azure Login
        run: az account show --query '{tenantId:tenantId,subscriptionId:id,user:user.name}' -o table

      # Apply直後のstateからoutput取得→$webへアップロード
      - name: App Deploy to Azure Static Website
        run: |
          set -euo pipefail
          SA_NAME="$(terraform -chdir=envs/azure/azure-b1s-mvp output -raw storage_account_name)"
          echo "Storage Account: $SA_NAME"

          # 配信ソースの優先順: app-landing > app/dist > app
          SRC_DIR=""
          for d in "app-landing" "app/dist" "app"; do
            if [ -d "$d" ]; then SRC_DIR="$d"; break; fi
          done
          [ -n "$SRC_DIR" ] || SRC_DIR="app"

          # 最低限のプレースホルダ（無い場合のみ）
          mkdir -p "$SRC_DIR"
          if [ ! -f "$SRC_DIR/index.html" ]; then
            printf '%s\n' \
              "<!doctype html><meta charset=utf-8><title>SRE IaC Starter</title><h1>SRE IaC Starter</h1><p>Deployed: $(date -u +%FT%TZ)</p>" \
              > "$SRC_DIR/index.html"
          fi

          # $web はクォート（リテラル）
          az storage blob upload-batch --account-name "$SA_NAME" -s "$SRC_DIR" -d '$web' --overwrite --auth-mode login

          echo "URL:"
          az storage account show -n "$SA_NAME" --query "primaryEndpoints.web" -o tsv
