name: terraform-apply
on:
  push:
    branches: [main]
    paths:
      - "envs/**"
      - "modules/**"

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      # validate は backend 無効で OK（PR と同じ条件）
      - name: Terraform Validate (Azure)
        run: |
          terraform -chdir=envs/azure/azure-b1s-mvp init -backend=false
          terraform -chdir=envs/azure/azure-b1s-mvp validate

      # apply は backend 有効で実行（Secrets から SP 認証）
      - name: Terraform Apply (Azure)
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        run: |
          terraform -chdir=envs/azure/azure-b1s-mvp init
          terraform -chdir=envs/azure/azure-b1s-mvp apply -auto-approve
